[build]
  base    = "frontend"
  command = "npm ci --no-audit --no-fund && npm run build"
  publish = "dist/frontend/browser"

[build.environment]
  NODE_VERSION = "20.19.0"
[[redirects]]
  from = "/api/*"
  to = "https://saves-loose-yourself-notified.trycloudflare.com//api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

